{% set name = "fpdf" %}
{% set version = "1.7.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fpdf-{{ version }}.tar.gz
  sha256: 125840783289e7d12552b1e86ab692c37322e7a65b96a99e0ea86cca041b6779

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - fpdf
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/reingart/pyfpdf
  summary: Simple PDF generation for Python
  license: LGPLv3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rpaframework-core
